version: "3"

services:
  development-plexexport-php:
    build: ./build
    image: ex0nuss/plex-export-docker
    container_name: frontend-plexexport-php
    restart: unless-stopped
    volumes:
      - ./data-plexexport:/data
    environment:
      - PLEX_URL=http://192.168.178.100:32400
      - PLEX_SECTIONS=Filme,Serien
      - PLEX_TOKEN=XXX
      - PLEX_INTERVAL=360m
    labels:
      - com.centurylinklabs.watchtower.enable=false
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "4"

  development-plexexport-nginx:
    image: nginx:latest
    container_name: frontend-plexexport-nginx
    restart: unless-stopped
    ports:
      - 9999:80
    volumes:
      - ./data-plexexport:/data
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - development-plexexport-php
    labels:
      - com.centurylinklabs.watchtower.enable=false
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "4"

### ENV-file presets ###
# Europe/Berlin
# 996
